### ISSUE TITLE
Document link testing desert

### ISSUE THREAD

**Issue by bluetyson** [kensanata/text-mapper#2]
I pulled the link out of a test map

https://campaignwiki.org/text-mapper/alpine/document?height=24&width=26&peaks=3&peak=7&steepness=5&arid=0&desert=1&seed=285556023

no bumps I think?

and get a nice rainbow unicorn velociraptor

![image](https://user-images.githubusercontent.com/17399794/216855177-6798344d-b2af-425e-8519-3feb45bc829c.png)

**Comment by bluetyson** [comment]
This one https://campaignwiki.org/text-mapper/alpine/random/interactive?width=50&bottom=0&peaks=3&bumps=2&height=20&steepness=4&peak=7&bump=2&arid=0&step=20&desert=1&type=hex 

https://campaignwiki.org/text-mapper/alpine/document?height=20 is the link at 'documented'

and

dug out of the source

<html>
<body>


# Seed: 96686220
--
  | # Documentation: https://campaignwiki.org/text-mapper/alpine/document?width=50&bottom=0&peaks=3&bumps=2&height=20&steepness=4&peak=7&bump=2&arid=0&step=20&desert=1&type=hex&seed=96686220


</body>
</html>

which also gives me a rainbow uniraptor - but the link looks ok there?

**Comment by bluetyson** [comment]
This one I generated from the 'fill in the boxes' textmapper form.

https://campaignwiki.org/text-mapper/alpine/random/interactive?width=26&bottom=0&peaks=3&bumps=2&height=24&steepness=4&peak=7&bump=2&arid=0&step=20&desert=1&type=hex  

<html>
<body>


# Seed: 912184623
--
  | # Documentation: https://campaignwiki.org/text-mapper/alpine/document?width=26&bottom=0&peaks=3&bumps=2&height=24&steepness=4&peak=7&bump=2&arid=0&step=20&desert=1&type=hex&seed=912184623


</body>
</html>

**Comment by kensanata** [comment]
I think I fixed it with  e87070eef.

**Comment by RichardScottOZ** [comment]
Ok, I will give it a shot.

**Comment by bluetyson** [comment]
Ok, will take a look, thanks.

**Comment by bluetyson** [comment]
With desert = 1 - should it be more red?  or the example here, showing the default?

https://campaignwiki.org/text-mapper/alpine/document?width=26&bottom=0&peaks=3&bumps=2&height=24&steepness=4&peak=7&bump=2&arid=0&step=20&desert=1&type=hex&seed=912184623

**Comment by bluetyson** [comment]
starting one from scratch seems the same though

https://campaignwiki.org/text-mapper/alpine/document?width=26&bottom=0&peaks=1&bumps=2&height=24&steepness=3&peak=7&bump=2&arid=0&climate=desert&type=hex&seed=990413375 

![image](https://user-images.githubusercontent.com/17399794/216929066-ded46bd2-3418-43ab-b6b3-f2c223f17925.png)

**Comment by kensanata** [comment]
> https://campaignwiki.org/text-mapper/alpine/document?width=26&bottom=0&peaks=3&bumps=2&height=24&steepness=4&peak=7&bump=2&arid=0&step=20&climate=desert&type=hex&seed=912184623
> 
I just changed from “desert=1” to “climate=desert” (in preparation for future extensions).

I hope the application doesn’t generate links with desert=1 anymore? Perhaps I forget to fix that somewhere.

**Comment by RichardScottOZ** [comment]
ah that could be it - would have to change the querystring to be climate=desert?

**Comment by bluetyson** [comment]
ah that could be it - would have to change the querystring to be climate=desert?

**Comment by kensanata** [comment]
Yes, exactly.

**Comment by kensanata** [comment]
I added the Australian desert example here: https://campaignwiki.org/text-mapper/alpine/parameters at the end.
